"""User Date Time Field added

Revision ID: 720c041f794e
Revises: 41dfcc6d425d
Create Date: 2018-12-24 01:55:25.392759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720c041f794e'
down_revision = '41dfcc6d425d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
